version: '3.3'
services:
    api:
        container_name: api
        depends_on:
            - db
        build: .
        ports:
            - '3000:3000'
    db:
        container_name: db
        image: postgres:12.8
        environment:
            POSTGRES_DB: jvnm
        env_file:
            - .env
        ports:
            - '5432:5432'
